// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ExperienceMultiplierHistory struct {
	ID             uuid.UUID
	UserID         uuid.NullUUID
	OldMultiplier  sql.NullString
	NewMultiplier  sql.NullString
	AcceptedBudget sql.NullString
	ShownBudget    sql.NullString
	Alpha          sql.NullString
	CreatedAt      sql.NullTime
}

type Skill struct {
	ID         uuid.UUID
	Name       string
	CategoryID uuid.NullUUID
	CreatedAt  sql.NullTime
}

type Task struct {
	ID                uuid.UUID
	TaskGiverID       uuid.NullUUID
	CategoryID        uuid.UUID
	Budget            string
	DurationHours     sql.NullInt32
	ComplexityLevel   sql.NullString
	IsOnline          sql.NullBool
	Lat               sql.NullString
	Lng               sql.NullString
	RadiusKm          sql.NullInt32
	State             string
	PriorityStartedAt sql.NullTime
	ActiveStartedAt   sql.NullTime
	ExpiresAt         sql.NullTime
	AcceptedAt        sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type TaskAcceptance struct {
	ID                  uuid.UUID
	TaskID              uuid.NullUUID
	UserID              uuid.NullUUID
	AcceptedBudget      string
	ResponseTimeSeconds sql.NullInt32
	CreatedAt           sql.NullTime
}

type TaskNotification struct {
	ID          uuid.UUID
	TaskID      uuid.NullUUID
	UserID      uuid.NullUUID
	WaveNumber  sql.NullInt32
	OpenedAt    sql.NullTime
	RespondedAt sql.NullTime
	Status      sql.NullString
	CreatedAt   sql.NullTime
}

type TaskRequiredSkill struct {
	TaskID  uuid.UUID
	SkillID uuid.UUID
	IsCore  sql.NullBool
}

type TaskStateTransition struct {
	ID          uuid.UUID
	TaskID      uuid.NullUUID
	FromState   sql.NullString
	ToState     sql.NullString
	TriggeredBy sql.NullString
	CreatedAt   sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	Phone        sql.NullString
	PasswordHash string
	Role         string
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserBehaviorMetric struct {
	UserID                uuid.UUID
	AcceptanceRate        sql.NullString
	MedianResponseSeconds sql.NullInt32
	PushOpenRate          sql.NullString
	CompletionRate        sql.NullString
	ReliabilityScore      sql.NullString
	TotalTasksCompleted   sql.NullInt32
	TotalTasksAccepted    sql.NullInt32
	UpdatedAt             sql.NullTime
}

type UserProfile struct {
	UserID                 uuid.UUID
	ExperienceLevel        string
	ExperienceMultiplier   string
	Mab                    string
	RadiusKm               int32
	FixedLat               sql.NullString
	FixedLng               sql.NullString
	Timezone               sql.NullString
	Language               sql.NullString
	ProfileCompletionScore sql.NullInt32
	LastActiveAt           sql.NullTime
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
}

type UserSkill struct {
	UserID    uuid.UUID
	SkillID   uuid.UUID
	IsPrimary sql.NullBool
}
