// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const acceptTaskStateUpdate = `-- name: AcceptTaskStateUpdate :exec
UPDATE tasks
SET state = 'accepted',
    accepted_at = NOW()
WHERE id = $1
`

func (q *Queries) AcceptTaskStateUpdate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, acceptTaskStateUpdate, id)
	return err
}

const addTaskRequiredSkill = `-- name: AddTaskRequiredSkill :exec

INSERT INTO task_required_skills (task_id, skill_id, is_core)
VALUES ($1,$2,$3)
`

type AddTaskRequiredSkillParams struct {
	TaskID  uuid.UUID
	SkillID uuid.UUID
	IsCore  sql.NullBool
}

// ============================================================
// TASK REQUIRED SKILLS
// ============================================================
func (q *Queries) AddTaskRequiredSkill(ctx context.Context, arg AddTaskRequiredSkillParams) error {
	_, err := q.db.ExecContext(ctx, addTaskRequiredSkill, arg.TaskID, arg.SkillID, arg.IsCore)
	return err
}

const addUserSkill = `-- name: AddUserSkill :exec

INSERT INTO user_skills (user_id, skill_id, is_primary)
VALUES ($1,$2,$3)
ON CONFLICT DO NOTHING
`

type AddUserSkillParams struct {
	UserID    uuid.UUID
	SkillID   uuid.UUID
	IsPrimary sql.NullBool
}

// ============================================================
// USER SKILLS
// ============================================================
func (q *Queries) AddUserSkill(ctx context.Context, arg AddUserSkillParams) error {
	_, err := q.db.ExecContext(ctx, addUserSkill, arg.UserID, arg.SkillID, arg.IsPrimary)
	return err
}

const createTaskPriority = `-- name: CreateTaskPriority :one

INSERT INTO tasks (
    task_giver_id,
    category_id,
    budget,
    duration_hours,
    complexity_level,
    is_online,
    lat,
    lng,
    radius_km,
    state,
    priority_started_at,
    expires_at
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7,$8,$9,
    'priority',
    NOW(),
    NOW() + INTERVAL '24 hours'
)
RETURNING id, task_giver_id, category_id, budget, duration_hours, complexity_level, is_online, lat, lng, radius_km, state, priority_started_at, active_started_at, expires_at, accepted_at, created_at, updated_at
`

type CreateTaskPriorityParams struct {
	TaskGiverID     uuid.NullUUID
	CategoryID      uuid.UUID
	Budget          string
	DurationHours   sql.NullInt32
	ComplexityLevel sql.NullString
	IsOnline        sql.NullBool
	Lat             sql.NullString
	Lng             sql.NullString
	RadiusKm        sql.NullInt32
}

// ============================================================
// TASKS
// ============================================================
func (q *Queries) CreateTaskPriority(ctx context.Context, arg CreateTaskPriorityParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTaskPriority,
		arg.TaskGiverID,
		arg.CategoryID,
		arg.Budget,
		arg.DurationHours,
		arg.ComplexityLevel,
		arg.IsOnline,
		arg.Lat,
		arg.Lng,
		arg.RadiusKm,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskGiverID,
		&i.CategoryID,
		&i.Budget,
		&i.DurationHours,
		&i.ComplexityLevel,
		&i.IsOnline,
		&i.Lat,
		&i.Lng,
		&i.RadiusKm,
		&i.State,
		&i.PriorityStartedAt,
		&i.ActiveStartedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, phone, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, phone, password_hash, role, status, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Phone        sql.NullString
	PasswordHash string
	Role         string
}

// ============================================================
// USERS
// ============================================================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :exec

INSERT INTO user_profiles (
    user_id,
    experience_level,
    experience_multiplier,
    mab,
    radius_km,
    fixed_lat,
    fixed_lng,
    timezone,
    language,
    last_active_at
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW())
`

type CreateUserProfileParams struct {
	UserID               uuid.UUID
	ExperienceLevel      string
	ExperienceMultiplier string
	Mab                  string
	RadiusKm             int32
	FixedLat             sql.NullString
	FixedLng             sql.NullString
	Timezone             sql.NullString
	Language             sql.NullString
}

// ============================================================
// USER PROFILE
// ============================================================
func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, createUserProfile,
		arg.UserID,
		arg.ExperienceLevel,
		arg.ExperienceMultiplier,
		arg.Mab,
		arg.RadiusKm,
		arg.FixedLat,
		arg.FixedLng,
		arg.Timezone,
		arg.Language,
	)
	return err
}

const expireTasks = `-- name: ExpireTasks :exec
UPDATE tasks
SET state = 'expired'
WHERE state IN ('priority','active')
AND expires_at <= NOW()
`

func (q *Queries) ExpireTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireTasks)
	return err
}

const getAcceptanceLatencyP50 = `-- name: GetAcceptanceLatencyP50 :one

SELECT percentile_cont(0.5)
WITHIN GROUP (ORDER BY response_time_seconds)
FROM task_acceptances
WHERE created_at >= NOW() - INTERVAL '7 days'
`

// ============================================================
// METRICS
// ============================================================
func (q *Queries) GetAcceptanceLatencyP50(ctx context.Context) (float64, error) {
	row := q.db.QueryRowContext(ctx, getAcceptanceLatencyP50)
	var percentile_cont float64
	err := row.Scan(&percentile_cont)
	return percentile_cont, err
}

const getActiveTasksForUser = `-- name: GetActiveTasksForUser :many


SELECT id, task_giver_id, category_id, budget, duration_hours, complexity_level, is_online, lat, lng, radius_km, state, priority_started_at, active_started_at, expires_at, accepted_at, created_at, updated_at
FROM tasks
WHERE state = 'active'
AND expires_at > NOW()
AND category_id = ANY($1)
AND budget >= $2
ORDER BY created_at DESC
LIMIT $3
`

type GetActiveTasksForUserParams struct {
	CategoryID uuid.UUID
	Budget     string
	Limit      int32
}

// ============================================================
// ACTIVE MARKETPLACE
// ============================================================
// $1 = []uuid categories
// $2 = min_budget
// $3 = limit
func (q *Queries) GetActiveTasksForUser(ctx context.Context, arg GetActiveTasksForUserParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTasksForUser, arg.CategoryID, arg.Budget, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskGiverID,
			&i.CategoryID,
			&i.Budget,
			&i.DurationHours,
			&i.ComplexityLevel,
			&i.IsOnline,
			&i.Lat,
			&i.Lng,
			&i.RadiusKm,
			&i.State,
			&i.PriorityStartedAt,
			&i.ActiveStartedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBehaviorMetrics = `-- name: GetBehaviorMetrics :one
SELECT user_id, acceptance_rate, median_response_seconds, push_open_rate, completion_rate, reliability_score, total_tasks_completed, total_tasks_accepted, updated_at
FROM user_behavior_metrics
WHERE user_id = $1
`

func (q *Queries) GetBehaviorMetrics(ctx context.Context, userID uuid.UUID) (UserBehaviorMetric, error) {
	row := q.db.QueryRowContext(ctx, getBehaviorMetrics, userID)
	var i UserBehaviorMetric
	err := row.Scan(
		&i.UserID,
		&i.AcceptanceRate,
		&i.MedianResponseSeconds,
		&i.PushOpenRate,
		&i.CompletionRate,
		&i.ReliabilityScore,
		&i.TotalTasksCompleted,
		&i.TotalTasksAccepted,
		&i.UpdatedAt,
	)
	return i, err
}

const getEligibleCandidates = `-- name: GetEligibleCandidates :many


SELECT
    u.id AS user_id,
    up.experience_level,
    up.experience_multiplier,
    up.mab,
    up.radius_km,
    up.fixed_lat,
    up.fixed_lng,
    ubm.acceptance_rate,
    ubm.median_response_seconds,
    ubm.push_open_rate,
    ubm.completion_rate,
    ubm.reliability_score,
    ubm.total_tasks_completed
FROM users u
JOIN user_profiles up ON up.user_id = u.id
JOIN user_behavior_metrics ubm ON ubm.user_id = u.id
WHERE
    u.status = 'active'
    AND up.last_active_at >= NOW() - INTERVAL '7 days'
    AND $1 >= (0.5 * up.mab)
    AND EXISTS (
        SELECT 1
        FROM user_skills us
        JOIN task_required_skills trs ON trs.skill_id = us.skill_id AND trs.task_id = $2
        WHERE us.user_id = u.id
    )
`

type GetEligibleCandidatesParams struct {
	Mab    string
	TaskID uuid.UUID
}

type GetEligibleCandidatesRow struct {
	UserID                uuid.UUID
	ExperienceLevel       string
	ExperienceMultiplier  string
	Mab                   string
	RadiusKm              int32
	FixedLat              sql.NullString
	FixedLng              sql.NullString
	AcceptanceRate        sql.NullString
	MedianResponseSeconds sql.NullInt32
	PushOpenRate          sql.NullString
	CompletionRate        sql.NullString
	ReliabilityScore      sql.NullString
	TotalTasksCompleted   sql.NullInt32
}

// ============================================================
// HARD FILTER CANDIDATE QUERY (LIB/PQ SAFE)
// ============================================================
// $1 = task_budget (numeric)
// $2 = task_id (uuid)
func (q *Queries) GetEligibleCandidates(ctx context.Context, arg GetEligibleCandidatesParams) ([]GetEligibleCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEligibleCandidates, arg.Mab, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEligibleCandidatesRow
	for rows.Next() {
		var i GetEligibleCandidatesRow
		if err := rows.Scan(
			&i.UserID,
			&i.ExperienceLevel,
			&i.ExperienceMultiplier,
			&i.Mab,
			&i.RadiusKm,
			&i.FixedLat,
			&i.FixedLng,
			&i.AcceptanceRate,
			&i.MedianResponseSeconds,
			&i.PushOpenRate,
			&i.CompletionRate,
			&i.ReliabilityScore,
			&i.TotalTasksCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationWasteRatio = `-- name: GetNotificationWasteRatio :one
SELECT
    COUNT(*) FILTER (WHERE status = 'ignored')::decimal
    / NULLIF(COUNT(*),0)
FROM task_notifications
WHERE created_at >= NOW() - INTERVAL '7 days'
`

func (q *Queries) GetNotificationWasteRatio(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getNotificationWasteRatio)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, task_giver_id, category_id, budget, duration_hours, complexity_level, is_online, lat, lng, radius_km, state, priority_started_at, active_started_at, expires_at, accepted_at, created_at, updated_at
FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskGiverID,
		&i.CategoryID,
		&i.Budget,
		&i.DurationHours,
		&i.ComplexityLevel,
		&i.IsOnline,
		&i.Lat,
		&i.Lng,
		&i.RadiusKm,
		&i.State,
		&i.PriorityStartedAt,
		&i.ActiveStartedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, task_giver_id, category_id, budget, duration_hours, complexity_level, is_online, lat, lng, radius_km, state, priority_started_at, active_started_at, expires_at, accepted_at, created_at, updated_at
FROM tasks
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetTaskForUpdate(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskForUpdate, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskGiverID,
		&i.CategoryID,
		&i.Budget,
		&i.DurationHours,
		&i.ComplexityLevel,
		&i.IsOnline,
		&i.Lat,
		&i.Lng,
		&i.RadiusKm,
		&i.State,
		&i.PriorityStartedAt,
		&i.ActiveStartedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskRequiredSkills = `-- name: GetTaskRequiredSkills :many
SELECT skill_id
FROM task_required_skills
WHERE task_id = $1
`

func (q *Queries) GetTaskRequiredSkills(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getTaskRequiredSkills, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var skill_id uuid.UUID
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, password_hash, role, status, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileForUpdate = `-- name: GetUserProfileForUpdate :one
SELECT user_id, experience_level, experience_multiplier, mab, radius_km, fixed_lat, fixed_lng, timezone, language, profile_completion_score, last_active_at, created_at, updated_at
FROM user_profiles
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) GetUserProfileForUpdate(ctx context.Context, userID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileForUpdate, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.ExperienceLevel,
		&i.ExperienceMultiplier,
		&i.Mab,
		&i.RadiusKm,
		&i.FixedLat,
		&i.FixedLng,
		&i.Timezone,
		&i.Language,
		&i.ProfileCompletionScore,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSkills = `-- name: GetUserSkills :many
SELECT skill_id
FROM user_skills
WHERE user_id = $1
`

func (q *Queries) GetUserSkills(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getUserSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var skill_id uuid.UUID
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAcceptedTasks = `-- name: IncrementAcceptedTasks :exec
UPDATE user_behavior_metrics
SET total_tasks_accepted = total_tasks_accepted + 1,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementAcceptedTasks(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementAcceptedTasks, userID)
	return err
}

const incrementCompletedTasks = `-- name: IncrementCompletedTasks :exec
UPDATE user_behavior_metrics
SET total_tasks_completed = total_tasks_completed + 1,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) IncrementCompletedTasks(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementCompletedTasks, userID)
	return err
}

const initUserBehaviorMetrics = `-- name: InitUserBehaviorMetrics :exec

INSERT INTO user_behavior_metrics (user_id)
VALUES ($1)
`

// ============================================================
// USER BEHAVIOR METRICS
// ============================================================
func (q *Queries) InitUserBehaviorMetrics(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, initUserBehaviorMetrics, userID)
	return err
}

const insertEMHistory = `-- name: InsertEMHistory :exec

INSERT INTO experience_multiplier_history (
    user_id,
    old_multiplier,
    new_multiplier,
    accepted_budget,
    shown_budget,
    alpha
)
VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertEMHistoryParams struct {
	UserID         uuid.NullUUID
	OldMultiplier  sql.NullString
	NewMultiplier  sql.NullString
	AcceptedBudget sql.NullString
	ShownBudget    sql.NullString
	Alpha          sql.NullString
}

// ============================================================
// EXPERIENCE MULTIPLIER HISTORY
// ============================================================
func (q *Queries) InsertEMHistory(ctx context.Context, arg InsertEMHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertEMHistory,
		arg.UserID,
		arg.OldMultiplier,
		arg.NewMultiplier,
		arg.AcceptedBudget,
		arg.ShownBudget,
		arg.Alpha,
	)
	return err
}

const insertTaskAcceptance = `-- name: InsertTaskAcceptance :exec

INSERT INTO task_acceptances (
    task_id,
    user_id,
    accepted_budget,
    response_time_seconds
)
VALUES ($1,$2,$3,$4)
`

type InsertTaskAcceptanceParams struct {
	TaskID              uuid.NullUUID
	UserID              uuid.NullUUID
	AcceptedBudget      string
	ResponseTimeSeconds sql.NullInt32
}

// ============================================================
// TASK ACCEPTANCE (RACE SAFE)
// ============================================================
func (q *Queries) InsertTaskAcceptance(ctx context.Context, arg InsertTaskAcceptanceParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskAcceptance,
		arg.TaskID,
		arg.UserID,
		arg.AcceptedBudget,
		arg.ResponseTimeSeconds,
	)
	return err
}

const insertTaskNotificationsBulk = `-- name: InsertTaskNotificationsBulk :exec


INSERT INTO task_notifications (task_id, user_id, wave_number, status)
SELECT $1, unnest($2), $3, 'sent'
`

type InsertTaskNotificationsBulkParams struct {
	TaskID     uuid.NullUUID
	Unnest     interface{}
	WaveNumber sql.NullInt32
}

// ============================================================
// NOTIFICATIONS
// ============================================================
// $2 = []uuid via pq.Array()
func (q *Queries) InsertTaskNotificationsBulk(ctx context.Context, arg InsertTaskNotificationsBulkParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskNotificationsBulk, arg.TaskID, arg.Unnest, arg.WaveNumber)
	return err
}

const markNotificationOpened = `-- name: MarkNotificationOpened :exec
UPDATE task_notifications
SET opened_at = NOW(),
    status = 'opened'
WHERE task_id = $1
AND user_id = $2
`

type MarkNotificationOpenedParams struct {
	TaskID uuid.NullUUID
	UserID uuid.NullUUID
}

func (q *Queries) MarkNotificationOpened(ctx context.Context, arg MarkNotificationOpenedParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationOpened, arg.TaskID, arg.UserID)
	return err
}

const markNotificationResponded = `-- name: MarkNotificationResponded :exec
UPDATE task_notifications
SET responded_at = NOW(),
    status = $3
WHERE task_id = $1
AND user_id = $2
`

type MarkNotificationRespondedParams struct {
	TaskID uuid.NullUUID
	UserID uuid.NullUUID
	Status sql.NullString
}

func (q *Queries) MarkNotificationResponded(ctx context.Context, arg MarkNotificationRespondedParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationResponded, arg.TaskID, arg.UserID, arg.Status)
	return err
}

const moveTaskToActive = `-- name: MoveTaskToActive :exec
UPDATE tasks
SET state = 'active',
    active_started_at = NOW()
WHERE id = $1
AND state = 'priority'
`

func (q *Queries) MoveTaskToActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, moveTaskToActive, id)
	return err
}

const updateAcceptanceRate = `-- name: UpdateAcceptanceRate :exec
UPDATE user_behavior_metrics
SET acceptance_rate = $2,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateAcceptanceRateParams struct {
	UserID         uuid.UUID
	AcceptanceRate sql.NullString
}

func (q *Queries) UpdateAcceptanceRate(ctx context.Context, arg UpdateAcceptanceRateParams) error {
	_, err := q.db.ExecContext(ctx, updateAcceptanceRate, arg.UserID, arg.AcceptanceRate)
	return err
}

const updateExperienceMultiplier = `-- name: UpdateExperienceMultiplier :exec
UPDATE user_profiles
SET experience_multiplier = $2,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateExperienceMultiplierParams struct {
	UserID               uuid.UUID
	ExperienceMultiplier string
}

func (q *Queries) UpdateExperienceMultiplier(ctx context.Context, arg UpdateExperienceMultiplierParams) error {
	_, err := q.db.ExecContext(ctx, updateExperienceMultiplier, arg.UserID, arg.ExperienceMultiplier)
	return err
}

const updateLastActive = `-- name: UpdateLastActive :exec
UPDATE user_profiles
SET last_active_at = NOW()
WHERE user_id = $1
`

func (q *Queries) UpdateLastActive(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLastActive, userID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = $2
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
